#!/usr/bin/env bash
#
# Google Scholar Profile Display - automated browser-assisted sync.
#
# Generated by the plugin's "Download Sync Script" button in wp-admin -
# your site URL, WordPress username, and a dedicated Application Password
# are already filled in below. Add this to cron/launchd on your own
# computer to keep your Scholar profile in sync without repeating the
# manual paste every time (Browser mode, plugin settings page).
#
# This file contains a live credential. Treat it like a password: do not
# commit it to version control or share it. Downloading a new copy from
# wp-admin revokes this one and issues a fresh credential.
#
# Usage:
#   ./scholar-sync.sh            run the sync
#   ./scholar-sync.sh --dry-run  fetch Scholar pages and print what would
#                                 be sent, without POSTing anything
#
# If "Full Author Lists" is enabled in settings: this script only fetches
# and POSTs the pages below. Expanding truncated author lists happens on
# the WordPress server after upload, same as Server mode - so it will not
# work if your server is the one blocked from Scholar. The bookmarklet
# resolves them from your browser instead, which does work in that case.

set -euo pipefail

SITE_URL="__SITE_URL__"
WP_USER="__WP_USER__"
APP_PASSWORD="__APP_PASSWORD__"
PROFILE_ID="__PROFILE_ID__"
MAX_PUBLICATIONS=__MAX_PUBLICATIONS__
IMPORT_URL="__IMPORT_URL__"
PAGE_SIZE=20

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="$SCRIPT_DIR/scholar-sync.log"
LOCK_FILE="$SCRIPT_DIR/scholar-sync.lock"
DRY_RUN=0

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') $1" | tee -a "$LOG_FILE"
}

fail() {
  log "ERROR: $1"
  exit 1
}

if [[ -f "$LOCK_FILE" ]]; then
  PREVIOUS_PID="$(cat "$LOCK_FILE")"
  if kill -0 "$PREVIOUS_PID" 2>/dev/null; then
    fail "Previous run (PID $PREVIOUS_PID) is still active, skipping."
  fi
fi
echo $$ > "$LOCK_FILE"
trap 'rm -f "$LOCK_FILE"' EXIT

import_page() {
  local html="$1"
  local mode="$2"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "[dry-run] would POST $mode (${#html} bytes of HTML) to $IMPORT_URL"
    return 0
  fi

  local response http_code body
  response="$(curl -sS -w '\n%{http_code}' \
    -u "${WP_USER}:${APP_PASSWORD}" \
    --data-urlencode "content=${html}" \
    --data-urlencode "import_mode=${mode}" \
    "${IMPORT_URL}")" || fail "Could not reach ${IMPORT_URL} (network error)"

  http_code="${response##*$'\n'}"
  body="${response%$'\n'*}"

  if (( http_code < 200 || http_code >= 300 )); then
    fail "Import request failed (HTTP $http_code): $body"
  fi
}

fetch_page() {
  local start="$1"
  curl -sS -f \
    "https://scholar.google.com/citations?user=${PROFILE_ID}&hl=en&cstart=${start}&pagesize=${PAGE_SIZE}" \
    || fail "Could not fetch Scholar page at cstart=${start}"
}

log "Starting sync for profile ${PROFILE_ID}"

MAIN_PAGE="$(fetch_page 0)"
import_page "$MAIN_PAGE" "replace"

# grep exits 1 on no match; || true keeps a legitimate zero-row page from aborting under set -e/pipefail
ROW_COUNT="$( { grep -o 'gsc_a_tr' <<<"$MAIN_PAGE" || true; } | wc -l | tr -d ' ')"
TOTAL=$ROW_COUNT
START=$PAGE_SIZE

while (( ROW_COUNT >= PAGE_SIZE && TOTAL < MAX_PUBLICATIONS )); do
  PAGE_HTML="$(fetch_page "$START")"
  # grep exits 1 on no match; || true keeps a legitimate zero-row page from aborting under set -e/pipefail
  ROW_COUNT="$( { grep -o 'gsc_a_tr' <<<"$PAGE_HTML" || true; } | wc -l | tr -d ' ')"

  if (( ROW_COUNT == 0 )); then
    break
  fi

  import_page "$PAGE_HTML" "append"
  TOTAL=$((TOTAL + ROW_COUNT))
  START=$((START + PAGE_SIZE))
done

log "Sync complete - processed approximately ${TOTAL} publications"
